/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Mathis
 */
public class RulesDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form RulesDialog
     * @param parent
     * @param modal
     */
    public RulesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setResizable(false);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        
        super.setLocationRelativeTo(null);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        goalLabel = new javax.swing.JLabel();
        modGame = new javax.swing.JLabel();
        modGamePicture1 = new javax.swing.JLabel();
        modGamePicture2 = new javax.swing.JLabel();
        modGamePicture3 = new javax.swing.JLabel();
        modGameLabel1 = new javax.swing.JLabel();
        modGameLabel2 = new javax.swing.JLabel();
        modGameLabel3 = new javax.swing.JLabel();
        modGame7 = new javax.swing.JLabel();
        movePicture1 = new javax.swing.JLabel();
        movePicture2 = new javax.swing.JLabel();
        movePicture3 = new javax.swing.JLabel();
        modGameLabel4 = new javax.swing.JLabel();
        modGameLabel5 = new javax.swing.JLabel();
        modGameLabel6 = new javax.swing.JLabel();
        modGameLabel7 = new javax.swing.JLabel();
        modGameLabel8 = new javax.swing.JLabel();
        modGameLabel9 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        goalLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        goalLabel.setText("<html><b>But du jeu :</b><br>  Avoir deux billes restantes sur le plateau en les<br>sortants grâce à la tuile colorée</html>");

        modGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modGame.setText("<html><b>Modes de jeux :</b></html>");

        modGamePicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_2J5B.png"))); // NOI18N

        modGamePicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_2J3B.png"))); // NOI18N

        modGamePicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_4J3B.png"))); // NOI18N

        modGameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel1.setText("2 joueurs 5 billes");

        modGameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel2.setText("2 joueurs 3 billes");

        modGameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel3.setText("4 joueurs 3 billes");

        modGame7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modGame7.setText("<html><b>Déplacements :</b></html>");

        movePicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_MB.png"))); // NOI18N
        movePicture1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                movePicture1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                movePicture1MouseExited(evt);
            }
        });

        movePicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_H.png"))); // NOI18N
        movePicture2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                movePicture2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                movePicture2MouseExited(evt);
            }
        });

        movePicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_V.png"))); // NOI18N
        movePicture3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                movePicture3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                movePicture3MouseExited(evt);
            }
        });

        modGameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel4.setText("Une rangée");

        modGameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel5.setText("Une rangée");

        modGameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel6.setText("Une bille");
        modGameLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        modGameLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel7.setText("en diagonale");
        modGameLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        modGameLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel8.setText("horizontalement");

        modGameLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modGameLabel9.setText("verticalement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goalLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modGame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modGameLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(movePicture1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(movePicture2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(movePicture3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modGameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modGameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modGameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modGameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modGameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modGameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modGamePicture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modGamePicture2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modGamePicture3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modGameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modGameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modGamePicture1)
                    .addComponent(modGamePicture2)
                    .addComponent(modGamePicture3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modGameLabel1)
                    .addComponent(modGameLabel3)
                    .addComponent(modGameLabel2))
                .addGap(18, 18, 18)
                .addComponent(modGame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movePicture1)
                    .addComponent(movePicture2)
                    .addComponent(movePicture3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modGameLabel6)
                    .addComponent(modGameLabel4)
                    .addComponent(modGameLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modGameLabel7)
                    .addComponent(modGameLabel9)
                    .addComponent(modGameLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void movePicture1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture1MouseEntered
        this.movePicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_MB_A.png")));
    }//GEN-LAST:event_movePicture1MouseEntered

    private void movePicture1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture1MouseExited
        this.movePicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_MB.png")));
    }//GEN-LAST:event_movePicture1MouseExited

    private void movePicture2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture2MouseEntered
        this.movePicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_H_A.png")));
    }//GEN-LAST:event_movePicture2MouseEntered

    private void movePicture2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture2MouseExited
        this.movePicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_H.png")));
    }//GEN-LAST:event_movePicture2MouseExited

    private void movePicture3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture3MouseEntered
        this.movePicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_V_A.png")));
    }//GEN-LAST:event_movePicture3MouseEntered

    private void movePicture3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movePicture3MouseExited
        this.movePicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules/Rules_ML_V.png")));
    }//GEN-LAST:event_movePicture3MouseExited
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goalLabel;
    private javax.swing.JLabel modGame;
    private javax.swing.JLabel modGame7;
    private javax.swing.JLabel modGameLabel1;
    private javax.swing.JLabel modGameLabel2;
    private javax.swing.JLabel modGameLabel3;
    private javax.swing.JLabel modGameLabel4;
    private javax.swing.JLabel modGameLabel5;
    private javax.swing.JLabel modGameLabel6;
    private javax.swing.JLabel modGameLabel7;
    private javax.swing.JLabel modGameLabel8;
    private javax.swing.JLabel modGameLabel9;
    private javax.swing.JLabel modGamePicture1;
    private javax.swing.JLabel modGamePicture2;
    private javax.swing.JLabel modGamePicture3;
    private javax.swing.JLabel movePicture1;
    private javax.swing.JLabel movePicture2;
    private javax.swing.JLabel movePicture3;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
